//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B403Blog.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.Resim1 = new HashSet<Resim>();
            this.Yorum = new HashSet<Yorum>();
            this.Etiket = new HashSet<Etiket>();
        }
    
        public int MakaleId { get; set; }
        [Required(ErrorMessage = "Açýklama alaný zorunludur!")]
        [StringLength(300, ErrorMessage = "En fazla 300 karakter girilebilir!", MinimumLength = 1)]
        public string Aciklama { get; set; }
        [Required(ErrorMessage = "Baþlýk alaný zorunludur!")]
        public string Baslik { get; set; }
        [Required(ErrorMessage = "Ýçerik alaný zorunludur!")]
        public string Icerik { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        [Required(ErrorMessage = "Kategori alaný zorunludur!")]
        public int KategoriID { get; set; }
        public int GoruntulenmeSayisi { get; set; }
        public int Begeni { get; set; }
        public int YazarID { get; set; }
        public Nullable<int> ResimID { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Resim Resim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resim> Resim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiket> Etiket { get; set; }
    }
}
